parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - import
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
env:
  es6: true
  browser: true
  node: true
settings:
  react:
    version: detect
rules:
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
      ignoreMemberSort: false
